version: '3.1'
services:
  mysql:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: dev
      # MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
